# 项目上下文配置
server:
  servlet:
    context-path: /o2o

# 响应被添加的前后缀
spring:
  mvc:
    view:
      prefix: /html/
      suffix: .html

# 数据源配置
c3p0:
  datasource:
    url: jdbc:mysql://localhost:3306/o2o?useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: 6BpJdfGz5FE=
    password: 6BpJdfGz5FE=
    driver-class-name: com.mysql.cj.jdbc.Driver


# Redis配置
rredis:
  hostname: 127.0.0.1
  port: 6379
  max-active: 100
  max-idle: 20
  max-wait: 3000
  test-on-borrow: true

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
  type-aliases-package: springboot.o2ov1.entity

# 验证码配置: border属性值no 引号包裹，禁止被转义为false
kaptcha:
  border: 'no'
  image_height: 50
  image_width: 135
  font_color: red
  font_size: 43
  font_names: Arial
  random_str: QWERBNMKL98760
  length: 4
  noise_color: black


